//USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const  RESET_USER = 'RESET_USER'
export const SET_LOCATION = 'SET_LOCATION'
export const  CLEAR_CONTACT = 'CLEAR_CONTACT'
export const SET_USER_AVAILABILITIES = 'SET_USER_AVAILABILITIES'
export const CLEAR_USER_AVAILABILITIES = 'CLEAR_USER_AVAILABILITIES'
export const UPDATE_AVAILABILITIES = 'UPDATE_AVAILABILITIES'
export const DELETE_AVAILABILITIES = 'DELETE_AVAILABILITIES'
export const CALCULATE_DISTANCE = 'CALCULATE_DISTANCE'

//UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const  RESET_UI = 'RESET_UI'
export const  SET_MESSAGE = 'SET_MESSAGE'
export const  CLEAR_MESSAGE = 'CLEAR_MESSAGE'

//DATA REDUCER TYPES
export const LOADING_DATA = 'LOADING_DATA';
export const CLEAR_LOADING_DATA = 'CLEAR_LOADING_DATA'
export const  RESET_DATA = 'RESET_DATA'
export const  CONTACT = 'CONTACT'
export const SET_AVAILABILITIES = 'SET_AVAILABILITIES'
export const CLEAR_AVAILABILITIES = 'CLEAR_AVAILABILITIES'